/**
 * Which of the three voices a heading opens, if any.
 *
 * Section 4 is the intellectual core of the whole brief: what the source says,
 * what the reader makes of it, and what the reader wants to know are three
 * different kinds of claim, and mixing them is how a literature note quietly
 * becomes a set of assertions nobody can trace.
 *
 * Stored as ordinary markdown headings rather than a schema, so the separation
 * survives export, another editor, and this program not existing. That makes it
 * a convention: the app can render the three differently and warn, but it
 * cannot enforce, and pretending otherwise would forfeit the portability that
 * makes the note worth keeping.
 *
 * The trailing part is free: "Source says · p. 6" is still the source's voice.
 */

export type Voice = "source" | "interpretation" | "question";

const OPENERS: ReadonlyArray<{ voice: Voice; match: RegExp }> = [
  // "Source", "Source says", "The source says", "Author says".
  { voice: "source", match: /^(the\s+)?(source|author|paper)(\s+says)?\b/i },
  // The literature-note template's own source-voice headings. "Key evidence"
  // and "Important quotes" are the paper's claims, not the reader's, and a
  // note generated by this app must not be the one place the three voices
  // stop being distinguishable.
  { voice: "source", match: /^(key\s+)?evidence\b/i },
  { voice: "source", match: /^(important\s+|key\s+)?quotes?\b/i },
  { voice: "source", match: /^abstract\b/i },
  { voice: "interpretation", match: /^(my\s+)?interpretation\b/i },
  // "My question", and the template's "Research questions".
  { voice: "question", match: /^(my\s+|research\s+|open\s+)?questions?\b/i },
];

export function voiceOf(headingText: string): Voice | null {
  const text = headingText.trim();
  for (const { voice, match } of OPENERS) {
    if (match.test(text)) return voice;
  }
  return null;
}

/** The heading each voice is written as when the template inserts it. */
export const VOICE_HEADINGS: Record<Voice, string> = {
  source: "Source says",
  interpretation: "My interpretation",
  question: "My question",
};

/**
 * The body a literature note starts from.
 *
 * Only ever inserted into an empty note, so it can never overwrite anything.
 */
export const LITERATURE_TEMPLATE = [
  `## ${VOICE_HEADINGS.source}`,
  "",
  "> ",
  "",
  `## ${VOICE_HEADINGS.interpretation}`,
  "",
  "",
  `## ${VOICE_HEADINGS.question}`,
  "",
  "",
].join("\n");
