import { useState } from "react";
import { AI_TASKS, aiApi, type AiDraft, type AiTask } from "../vault/api";

/**
 * Optional assistance, in the context panel, marked as generated throughout.
 *
 * Three rules from the brief are visible here rather than merely honoured:
 *
 * - **Inert until accepted.** A draft is text on screen and nothing else.
 *   There is no autosave of it, no partial application, no "undo" needed —
 *   discarding is closing it, because nothing has happened yet.
 * - **Marked as generated.** Dashed border, the model's name on every draft,
 *   and a different ground from the note. It must not be possible to read this
 *   at a glance and think the note says it.
 * - **Accepted through the ordinary path.** Accepting calls the same save the
 *   editor calls. Generated text has no privileges over typed text, and there
 *   is exactly one way into a file.
 *
 * Switched off, this is a sentence and a link to settings — not a button that
 * fails when pressed.
 */
export default function AiPanel({
  ready,
  wanted,
  title,
  body,
  onAcceptText,
  onAcceptTags,
  onOpenSettings,
  onReport,
}: {
  /** Asking would actually reach something. */
  ready: boolean;
  /** The setting is on, whether or not a key was found. */
  wanted: boolean;
  title: string;
  body: string;
  /** Append prose to the note, through the same save typing goes through. */
  onAcceptText: (text: string) => void;
  onAcceptTags: (tags: string[]) => void;
  onOpenSettings: () => void;
  onReport: (message: string, cause: unknown) => void;
}) {
  const [draft, setDraft] = useState<AiDraft | null>(null);
  const [asking, setAsking] = useState<AiTask | null>(null);
  /** Which suggested tags are ticked. Nothing is ticked to begin with. */
  const [picked, setPicked] = useState<Set<string>>(new Set());

  async function ask(task: AiTask) {
    setAsking(task);
    setDraft(null);
    setPicked(new Set());
    try {
      setDraft(await aiApi.suggest(task, title, body));
    } catch (cause) {
      onReport("Could not ask", cause);
    } finally {
      setAsking(null);
    }
  }

  if (!ready) {
    return (
      <section>
        <h2 className="mb-2 text-xs font-semibold tracking-wide text-ink-muted uppercase">
          Assistance
        </h2>
        <p className="text-sm text-ink-muted">
          {wanted ? (
            <>
              Switched on, but there is no API key to use.{" "}
              <button
                type="button"
                onClick={onOpenSettings}
                className="text-accent underline underline-offset-2"
              >
                Add one
              </button>
              , or set{" "}
              <code className="font-mono text-xs">ANTHROPIC_API_KEY</code> and
              reopen Sutra.
            </>
          ) : (
            <>
              Off. Everything else in this panel is computed from your vault and
              can show its working;{" "}
              <button
                type="button"
                onClick={onOpenSettings}
                className="text-accent underline underline-offset-2"
              >
                switching this on
              </button>{" "}
              adds a model that cannot.
            </>
          )}
        </p>
      </section>
    );
  }

  return (
    <section>
      <h2 className="mb-2 text-xs font-semibold tracking-wide text-ink-muted uppercase">
        Assistance
      </h2>
      <ul className="flex flex-col gap-1">
        {AI_TASKS.map((item) => (
          <li key={item.task}>
            <button
              type="button"
              disabled={asking !== null}
              onClick={() => void ask(item.task)}
              className="w-full rounded-lg border border-border px-3 py-1.5 text-left text-sm text-ink-soft transition-colors duration-150 ease-out hover:border-accent hover:text-accent disabled:opacity-50"
            >
              {asking === item.task ? "Asking…" : item.label}
            </button>
          </li>
        ))}
      </ul>

      {draft && (
        <div
          aria-label="Generated draft"
          // Dashed and on its own ground, so it cannot be mistaken at a glance
          // for anything the note says.
          className="mt-3 rounded-lg border border-dashed border-highlight bg-highlight-bg p-3"
        >
          <p className="mb-2 text-[0.6875rem] font-semibold tracking-wide text-highlight uppercase">
            Generated by {draft.model} · not saved
          </p>

          {draft.removedCitations.length > 0 && (
            <p className="mb-2 text-xs text-highlight">
              {draft.removedCitations.length === 1
                ? "It wrote a citation for a source this vault does not have. It was removed before you saw this."
                : `It wrote ${draft.removedCitations.length} citations for sources this vault does not have. They were removed before you saw this.`}
            </p>
          )}

          {draft.task === "tags" ? (
            <ul className="flex flex-col gap-1">
              {draft.lines.map((tag) => (
                <li key={tag}>
                  <label className="flex items-center gap-2 text-sm text-ink">
                    <input
                      type="checkbox"
                      checked={picked.has(tag)}
                      onChange={(e) =>
                        setPicked((prev) => {
                          const next = new Set(prev);
                          if (e.target.checked) next.add(tag);
                          else next.delete(tag);
                          return next;
                        })
                      }
                      className="accent-accent"
                    />
                    <span className="min-w-0 flex-1 truncate">#{tag}</span>
                  </label>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-sm whitespace-pre-wrap text-ink">
              {draft.task === "questions" ? draft.lines.join("\n") : draft.text}
            </p>
          )}

          {draft.lines.length === 0 && draft.text === "" && (
            <p className="text-sm text-ink-muted">It had nothing to say.</p>
          )}

          <div className="mt-3 flex justify-end gap-2">
            <button
              type="button"
              onClick={() => setDraft(null)}
              className="rounded-lg border border-border px-2.5 py-1 text-xs text-ink-soft transition-colors duration-150 ease-out hover:border-accent hover:text-accent"
            >
              Discard
            </button>
            <button
              type="button"
              disabled={draft.task === "tags" && picked.size === 0}
              onClick={() => {
                if (draft.task === "tags") onAcceptTags([...picked]);
                else
                  onAcceptText(
                    draft.task === "questions"
                      ? draft.lines.map((q) => `- ${q}`).join("\n")
                      : draft.text,
                  );
                setDraft(null);
              }}
              className="rounded-lg bg-accent px-2.5 py-1 text-xs font-medium text-surface transition-opacity duration-150 ease-out hover:opacity-90 disabled:opacity-50"
            >
              {draft.task === "tags"
                ? `Add ${picked.size === 1 ? "1 tag" : `${picked.size} tags`}`
                : "Add to the note"}
            </button>
          </div>
        </div>
      )}
    </section>
  );
}
